version: '3'
services:
  serviceregistry:
    image: '09f02eac5a99'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: '6cac1aebf8c3'
    container_name: configserver
    ports:
      - '9296:9296'
    depends_on:
      - serviceregistry
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka